80 api for cruding stacks protocol nodes
kotalco/community-api pull request #81
Opened 2023-03-21 16:35 UTC by mohamed-abdelrhman

2023-03-27 23:51 UTC, mFarghaly requested changes

2023-03-27 23:51 UTC, mFarghaly commented on internal/stacks/stacks_service.go
> +			NodePrivateKeySecretName: dto.NodePrivateKeySecretName,
NodePrivateKeySecretName is not required during creation.
Nodes get assigned a random identifier when no private key is given.
private key -> public key -> node id.

2023-03-28 23:06 UTC, mohamed-abdelrhman commented on api/url_mapping.go
> +	stacksNodesGroup.Post("/", stacks.Create, middleware.IsDuplicated)
yes it should,
i'll create separate PR for the remaining protocols

2023-03-28 23:20 UTC, mFarghaly approved these changes

2023-03-28 23:20 UTC, merged