fix: fix bitcoin/ipfs-peer listing
kotalco/community-api pull request #98
Opened 2023-04-28 18:05 UTC by mohamed-abdelrhman

2023-04-30 08:39 UTC, mFarghaly requested changes
**Summary:**
- type-cast all protocols into protocol type NOT pointer to type
- FromXYZNode should return struct not pointer to struct because we're modifying receiver
- don't use []*type, use []type

**Please Read:**
- https://philpearl.github.io/post/bad_go_slice_of_pointers/
- https://trstringer.com/golang-slice-references/
- https://stackoverflow.com/questions/23542989/pointers-vs-values-in-parameters-and-return-values

2023-04-30 08:39 UTC, mFarghaly commented on internal/bitcoin/bitcoin.go
> +type BitcoinListDto []*BitcoinDto
Use a slice of structs instead of a slice of pointer to structs.
Do the same for all other protocols

2023-04-30 08:39 UTC, mFarghaly commented on internal/bitcoin/bitcoin.go
> +func (dto BitcoinDto) FromBitcoinNode(n bitcoinv1alpha1.Node) *BitcoinDto {
return struct instead of pointer to a struct, because we're modifying a receiver.

Do the same for all protocols.

2023-05-01 07:30 UTC, mohamed-abdelrhman commented on api/handlers/bitcoin/bitcoin_handler.go
> +	updated, err := service.Update(dto, &node)
@mFarghaly 
as you can see we have to &protocol coz XYZ.service uses  pointer to protocol

2023-05-01 07:30 UTC, mohamed-abdelrhman commented on api/handlers/bitcoin/bitcoin_handler.go
>  }
@mFarghaly

2023-05-08 15:14 UTC, mFarghaly requested changes

2023-05-09 16:05 UTC, mohamed-abdelrhman commented on api/handlers/chainlink/chainlink_handler.go
> +	err := service.Update(*dto, &node)
because update service accept value not pointer to value so i had to dereference the dto

2023-05-09 16:07 UTC, merged